[alias]
today = "run --quiet --release --features today -- today"
scaffold = "run --quiet --release -- scaffold"
download = "run --quiet --release -- download"
read = "run --quiet --release -- read"

solve = "run --quiet --release -- solve"
all = "run --quiet --release -- all"
time = "run --quiet --release -- time"

[env]
AOC_YEAR = "2025"
ADVENT_OF_CODE_SESSION = "53616c7465645f5f1d26b470a2b210a9c2dbacaf4f7a376cc03cbfbe6bfd88433df52f31e530732944bda6474394da531b4001260ecd1ae2fd74ba9e4ba05a57"